### ISSUE TITLE
Utterance typos

### ISSUE THREAD

**Issue by Damcy** [google-research-datasets/dstc8-schema-guided-dialogue#12]
Many substrings of utterance(more than 1000 lines) match the pattern "[a-z0-9]\.[A-Z]", eg:

"No.Now I don't ```want.Thank``` ```you.That's``` all."(typos)

"I have 9 hotels for ```you.First``` with rating 4.4 is Anaheim Rv ```Park.Tell``` me your opinion."(typos)

"Arc The.Hotel"(this is a hotel name, this should be a correct format)

Is this normal?

**Comment by abhirast** [comment]
Thank you for reporting this. We chose to keep the raw utterances from the crowd workers in the dataset to keep them closer to utterances entered by an actual user to the dialogue system. Such utterances may contain inconsistent spaces, typos etc and hence we don't want to fix them. Please feel free to add any follow-ups here.
