### ISSUE TITLE
Slot value don't exactly map to utterance words

### ISSUE THREAD

**Issue by ksurya** [google-research-datasets/dstc8-schema-guided-dialogue#13]
File: `train/dialogues_059.json`
Dialogue ID: `59_00125`
Turn: 14

The slot `pickup_location` contains a value `Hartsfield\u2013Jackson`.

Utterances in this dialogue use ascii hyphen `-` for the slot value, but annotation has unicode `\u2013`.

**Comment by abhirast** [comment]
Thank you for raising this issue. We have just fixed similar errors in the dataset. We also welcome pull requests fixing similar issues.
