### ISSUE TITLE
Annotate error for non-categorical slots in dev set

### ISSUE THREAD

**Issue by ypruan** [google-research-datasets/dstc8-schema-guided-dialogue#15]
Hi, I found some annotate errors for  non-categorical slots, which are most for "destination_city/origin_city", some examples  like : 

- 1_00041 USER I want to fly from Mexico City to Seattle on the 11th of March. destination_city ['Mexico City']
- 1_00108 USER I want to go from Los Angeles to Delhi origin_city ['Delhi']
- 1_00116 USER I'm going to New York from Seattle. origin_city ['New York']
- 1_00116 USER I'm going to New York from Seattle. destination_city ['Seattle']
- 1_00041 USER I want to fly from Mexico City to Seattle on the 11th of March. origin_city ['Seattle']
- 1_00108 USER I want to go from Los Angeles to Delhi destination_city ['Los Angeles']

Maybe there're also annotation errors in training set, but I did not check it.

**Comment by XiaoxueZang** [comment]
Thanks for pointing them out. There were a few errors in the user utterances. We have fixed them. We welcome you to directly send pull requests to fix such errors. We’ll merge them after review.
