### ISSUE TITLE
slots belief state error

### ISSUE THREAD

**Issue by Leishuyu-bupt** [google-research-datasets/dstc8-schema-guided-dialogue#16]
In following dialogue, the origin city and destination city are annotated reversely.
"dialogue_id": "89_00000",
    "services": [
      "Buses_2",
      "Travel_1"
    ],
    "turns": [
      {
        "frames": [
          {
            "service": "Buses_2",
            "slots": [],
            "state": {
              "active_intent": "FindBus",
              "requested_slots": [],
              "slot_values": {}
            }
          }
        ],
        "speaker": "USER",
        "utterance": "Please help me find a bus."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "REQUEST",
                "slot": "destination",
                "values": []
              },
              {
                "act": "REQUEST",
                "slot": "origin",
                "values": []
              },
              {
                "act": "REQUEST",
                "slot": "departure_date",
                "values": []
              }
            ],
            "service": "Buses_2",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Sure, no problem. I'll need the following information: Your departure date, as well as your origin and destination cities."
      },
      {
        "frames": [
          {
            "service": "Buses_2",
            "slots": [
              {
                "exclusive_end": 32,
                "slot": "destination",
                "start": 24
              },
              {
                "exclusive_end": 41,
                "slot": "origin",
                "start": 36
              },
              {
                "exclusive_end": 57,
                "slot": "departure_date",
                "start": 45
              }
            ],
            "state": {
              "active_intent": "FindBus",
              "requested_slots": [],
              "slot_values": {
                "departure_date": [
                  "6th of March"
                ],
                "destination": [
                  "San Fran"
                ],
                "origin": [
                  "Vegas"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "I'd like to travel from San Fran to Vegas on 6th of March."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "OFFER",
                "slot": "departure_time",
                "values": [
                  "10:50 am"
                ]
              },
              {
                "act": "OFFER",
                "slot": "price",
                "values": [
                  "$50"
                ]
              },
              {
                "act": "OFFER",
                "slot": "fare_type",
                "values": [
                  "Economy"
                ]
              },
              {
                "act": "INFORM_COUNT",
                "slot": "count",
                "values": [
                  "6"
                ]
              }
            ],
            "service": "Buses_2",
            "slots": [
              {
                "exclusive_end": 65,
                "slot": "departure_time",
                "start": 57
              },
              {
                "exclusive_end": 76,
                "slot": "price",
                "start": 73
              }
            ]
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "I've found 6 buses that might interest you. How does the 10:50 am bus at $50 per Economy ticket sound?"
      },
      {
        "frames": [
          {
            "service": "Buses_2",
            "slots": [],
            "state": {
              "active_intent": "BuyBusTicket",
              "requested_slots": [],
              "slot_values": {
                "departure_date": [
                  "6th of March"
                ],
                "departure_time": [
                  "10:50 am"
                ],
                "destination": [
                  "San Fran"
                ],
                "fare_type": [
                  "Economy"
                ],
                "group_size": [
                  "2"
                ],
                "origin": [
                  "Vegas"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "I like that. Please get me 2 tickets on that bus."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "CONFIRM",
                "slot": "origin",
                "values": [
                  "Las Vegas"
                ]
              },
              {
                "act": "CONFIRM",
                "slot": "destination",
                "values": [
                  "San Francisco"
                ]
              },
              {
                "act": "CONFIRM",
                "slot": "departure_date",
                "values": [
                  "March 6th"
                ]
              },
              {
                "act": "CONFIRM",
                "slot": "departure_time",
                "values": [
                  "10:50 am"
                ]
              },
              {
                "act": "CONFIRM",
                "slot": "group_size",
                "values": [
                  "2"
                ]
              },
              {
                "act": "CONFIRM",
                "slot": "fare_type",
                "values": [
                  "Economy"
                ]
              }
            ],
            "service": "Buses_2",
            "slots": [
              {
                "exclusive_end": 101,
                "slot": "origin",
                "start": 92
              },
              {
                "exclusive_end": 118,
                "slot": "destination",
                "start": 105
              },
              {
                "exclusive_end": 72,
                "slot": "departure_date",
                "start": 63
              },
              {
                "exclusive_end": 82,
                "slot": "departure_time",
                "start": 74
              }
            ]
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Sure. Please confirm that you'd like 2 Economy tickets for the March 6th, 10:50 am bus from Las Vegas to San Francisco."
      },
      {
        "frames": [
          {
            "service": "Buses_2",
            "slots": [],
            "state": {
              "active_intent": "BuyBusTicket",
              "requested_slots": [],
              "slot_values": {
                "departure_date": [
                  "6th of March",
                  "March 6th"
                ],
                "departure_time": [
                  "10:50 am"
                ],
                "destination": [
                  "San Fran",
                  "San Francisco"
                ],
                "fare_type": [
                  "Economy"
                ],
                "group_size": [
                  "1"
                ],
                "origin": [
                  "Las Vegas",
                  "Vegas"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "No, my travel partner has just cancelled. Please make that 1 ticket instead."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "CONFIRM",
                "slot": "departure_time",
                "values": [
                  "10:50 am"
                ]
              },
              {
                "act": "CONFIRM",
                "slot": "group_size",
                "values": [
                  "1"
                ]
              }
            ],
            "service": "Buses_2",
            "slots": [
              {
                "exclusive_end": 89,
                "slot": "departure_time",
                "start": 81
              }
            ]
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Okay, no problem. Please confirm that you'd like 1 ticket for the bus leaving at 10:50 am."
      },
      {
        "frames": [
          {
            "service": "Buses_2",
            "slots": [],
            "state": {
              "active_intent": "BuyBusTicket",
              "requested_slots": [],
              "slot_values": {
                "departure_date": [
                  "6th of March",
                  "March 6th"
                ],
                "departure_time": [
                  "10:50 am"
                ],
                "destination": [
                  "San Fran",
                  "San Francisco"
                ],
                "fare_type": [
                  "Economy"
                ],
                "group_size": [
                  "1"
                ],
                "origin": [
                  "Las Vegas",
                  "Vegas"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "That is correct."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "NOTIFY_SUCCESS",
                "slot": "",
                "values": []
              }
            ],
            "service": "Buses_2",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "I have successfully confirmed your ticket."
      },
      {
        "frames": [
          {
            "service": "Buses_2",
            "slots": [],
            "state": {
              "active_intent": "BuyBusTicket",
              "requested_slots": [],
              "slot_values": {
                "departure_date": [
                  "6th of March",
                  "March 6th"
                ],
                "departure_time": [
                  "10:50 am"
                ],
                "destination": [
                  "San Fran",
                  "San Francisco"
                ],
                "fare_type": [
                  "Economy"
                ],
                "group_size": [
                  "1"
                ],
                "origin": [
                  "Las Vegas",
                  "Vegas"
                ]
              }
            }
          },
          {
            "service": "Travel_1",
            "slots": [],
            "state": {
              "active_intent": "FindAttractions",
              "requested_slots": [],
              "slot_values": {
                "category": [
                  "dontcare"
                ],
                "good_for_kids": [
                  "True"
                ],
                "location": [
                  "San Fran",
                  "San Francisco"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "Thank you very much. You've been very helpful. Since my travel partner cancelled, I'd like to take my nephew living in Vegas to visit some attractions. Any child-friendly attractions you can recommend?"
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "OFFER",
                "slot": "attraction_name",
                "values": [
                  "Alcatraz Island"
                ]
              },
              {
                "act": "OFFER",
                "slot": "category",
                "values": [
                  "Historical Landmark"
                ]
              }
            ],
            "service": "Travel_1",
            "slots": [
              {
                "exclusive_end": 29,
                "slot": "attraction_name",
                "start": 14
              }
            ]
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "May I suggest Alcatraz Island, a Historical Landmark?"
      },
      {
        "frames": [
          {
            "service": "Travel_1",
            "slots": [],
            "state": {
              "active_intent": "FindAttractions",
              "requested_slots": [],
              "slot_values": {
                "attraction_name": [
                  "Alcatraz Island"
                ],
                "category": [
                  "dontcare"
                ],
                "good_for_kids": [
                  "True"
                ],
                "location": [
                  "San Fran",
                  "San Francisco"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "Okay, cool. Thanks."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "REQ_MORE",
                "slot": "",
                "values": []
              }
            ],
            "service": "Travel_1",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Would you like my help with anything else?"
      },
      {
        "frames": [
          {
            "service": "Travel_1",
            "slots": [],
            "state": {
              "active_intent": "NONE",
              "requested_slots": [],
              "slot_values": {
                "attraction_name": [
                  "Alcatraz Island"
                ],
                "category": [
                  "dontcare"
                ],
                "good_for_kids": [
                  "True"
                ],
                "location": [
                  "San Fran",
                  "San Francisco"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "No. Thank you very much. You've been very helpful."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "GOODBYE",
                "slot": "",
                "values": []
              }
            ],
            "service": "Travel_1",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Enjoy yourselves!"
      }
    ]
  },

**Comment by XiaoxueZang** [comment]
Thank you for identifying this issue. We have just fixed it by editing the user utterance. We also welcome pull requests to fix similar errors. We’ll merge them after review.
