### ISSUE TITLE
The checking manner when evaluate the non-categorical slots

### ISSUE THREAD

**Issue by ypruan** [google-research-datasets/dstc8-schema-guided-dialogue#17]
Hi, I have run your published eval scripts. And it seems that the scripts using both the prediction for "start" and "end" position in 'slots' results but also "textual" values in "state" results  when evaluate the non-categorical slots,  so why do not only use the predicted "textual" values in "state" predictions?

**Comment by abhirast** [comment]
Thank you for the question. The metrics defined over the "slots" field are optional and are for evaluating the performance of slot tagging (if a model chooses to do it). The metric defined over the "state" field is a required metric (all participants must report it) and makes use of the textual values. Hope this helps. You may refer the README for more details. Please feel free to reach out if there are more questions.

**Comment by AtmaHou** [comment]
> Thank you for the question. The metrics defined over the "slots" field are optional and are for evaluating the performance of slot tagging (if a model chooses to do it). The metric defined over the "state" field is a required metric (all participants must report it) and makes use of the textual values. Hope this helps. You may refer the README for more details. Please feel free to reach out if there are more questions.

Same question and thanks for the answer!
