### ISSUE TITLE
Slots not in required/optional list do appear in states

### ISSUE THREAD

**Issue by ypruan** [google-research-datasets/dstc8-schema-guided-dialogue#19]
Hi, I found some slots not in required/optional list appeared in states too, like (Buses_1, FindBus, leaving_time in dial_2_00079), hope you can publish another accurately-cleaned dataset soon (this work can be done easily). Thanks!

**Comment by yobekiko** [comment]
I think they intended to annotate that, because the `leaving_time` slot is one of the required slots of intent `BuyBusTicket`. It looks reasonable for me: we need to keep tracking the required/optional slots for all intents in a given service.

**Comment by ypruan** [comment]
Yes, I got it. Thanks

**Comment by ypruan** [comment]
> I think they intended to annotate that, because the `leaving_time` slot is one of the required slots of intent `BuyBusTicket`. It looks reasonable for me: we need to keep tracking the required/optional slots for all intents in a given service.

Yes, you're right. Thanks!

**Comment by abhirast** [comment]
Thank you @yobekiko for the explanation!
