### ISSUE TITLE
empty utterance

### ISSUE THREAD

**Issue by jing-qian** [google-research-datasets/dstc8-schema-guided-dialogue#2]
file train/dialogues_21, 28 ,29, 30.json have dialogues with empty user utterances. file train/dialogues_21, 26, 28, 29, 30, 31.json have dialogues with empty system utterances.

**Comment by abhirast** [comment]
Thank you for bringing this to our notice. A few unclean dialogues from our initial collection made its way to the final version. We will post a cleaned version soon.

**Comment by abhirast** [comment]
We have either fixed or removed some of the dialogues which had unclean or empty utterances. Thank you again for reporting this issue.
