### ISSUE TITLE
label error

### ISSUE THREAD

**Issue by Leishuyu-bupt** [google-research-datasets/dstc8-schema-guided-dialogue#20]
In 12_00115, the theater name show be labelled with "THE LOT City Center" rather than "dontcare"
{
    "dialogue_id": "12_00115",
    "services": [
      "Movies_1"
    ],
    "turns": [
      {
        "frames": [
          {
            "service": "Movies_1",
            "slots": [],
            "state": {
              "active_intent": "FindMovies",
              "requested_slots": [],
              "slot_values": {}
            }
          }
        ],
        "speaker": "USER",
        "utterance": "I want to find a movie to watch"
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "REQUEST",
                "slot": "location",
                "values": []
              }
            ],
            "service": "Movies_1",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Would you prefer a certain location?"
      },
      {
        "frames": [
          {
            "service": "Movies_1",
            "slots": [
              {
                "exclusive_end": 27,
                "slot": "location",
                "start": 18
              }
            ],
            "state": {
              "active_intent": "FindMovies",
              "requested_slots": [],
              "slot_values": {
                "location": [
                  "Brentwood"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "Can you search in Brentwood."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "OFFER",
                "slot": "movie_name",
                "values": [
                  "Breakthrough",
                  "Captain Marvel",
                  "Dumbo"
                ]
              }
            ],
            "service": "Movies_1",
            "slots": [
              {
                "exclusive_end": 22,
                "slot": "movie_name",
                "start": 10
              },
              {
                "exclusive_end": 38,
                "slot": "movie_name",
                "start": 24
              },
              {
                "exclusive_end": 47,
                "slot": "movie_name",
                "start": 42
              }
            ]
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "How about Breakthrough, Captain Marvel or Dumbo?"
      },
      {
        "frames": [
          {
            "service": "Movies_1",
            "slots": [
              {
                "exclusive_end": 42,
                "slot": "location",
                "start": 33
              }
            ],
            "state": {
              "active_intent": "FindMovies",
              "requested_slots": [],
              "slot_values": {
                "location": [
                  "San Ramon"
                ],
                "theater_name": [
                  "dontcare"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "Please find some other movies in San Ramon. Any theatre is fine."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "OFFER",
                "slot": "movie_name",
                "values": [
                  "Hellboy",
                  "Little",
                  "Missing Link"
                ]
              }
            ],
            "service": "Movies_1",
            "slots": [
              {
                "exclusive_end": 17,
                "slot": "movie_name",
                "start": 10
              },
              {
                "exclusive_end": 25,
                "slot": "movie_name",
                "start": 19
              },
              {
                "exclusive_end": 41,
                "slot": "movie_name",
                "start": 29
              }
            ]
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "How about Hellboy, Little or Missing Link?"
      },
      {
        "frames": [
          {
            "service": "Movies_1",
            "slots": [],
            "state": {
              "active_intent": "FindMovies",
              "requested_slots": [],
              "slot_values": {
                "location": [
                  "San Ramon"
                ],
                "show_type": [
                  "3d"
                ],
                "theater_name": [
                  "dontcare"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "I want to watch 3d show, pls find other movies"
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "OFFER",
                "slot": "movie_name",
                "values": [
                  "Shazam!",
                  "Teen Spirit",
                  "The Curse of La Llorona"
                ]
              },
              {
                "act": "INFORM_COUNT",
                "slot": "count",
                "values": [
                  "3"
                ]
              }
            ],
            "service": "Movies_1",
            "slots": [
              {
                "exclusive_end": 35,
                "slot": "movie_name",
                "start": 28
              },
              {
                "exclusive_end": 48,
                "slot": "movie_name",
                "start": 37
              },
              {
                "exclusive_end": 75,
                "slot": "movie_name",
                "start": 52
              }
            ]
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "I found 3 movies. How about Shazam!, Teen Spirit or The Curse of La Llorona?"
      },
      {
        "frames": [
          {
            "service": "Movies_1",
            "slots": [
              {
                "exclusive_end": 11,
                "slot": "movie_name",
                "start": 0
              }
            ],
            "state": {
              "active_intent": "FindMovies",
              "requested_slots": [],
              "slot_values": {
                "location": [
                  "San Ramon"
                ],
                "movie_name": [
                  "Teen Spirit"
                ],
                "show_type": [
                  "3d"
                ],
                "theater_name": [
                  "dontcare"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "Teen Spirit is perfect."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "OFFER_INTENT",
                "slot": "intent",
                "values": [
                  "BuyMovieTickets"
                ]
              }
            ],
            "service": "Movies_1",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Would you like to purchase the tickets?"
      },
      {
        "frames": [
          {
            "service": "Movies_1",
            "slots": [
              {
                "exclusive_end": 35,
                "slot": "show_date",
                "start": 23
              }
            ],
            "state": {
              "active_intent": "GetTimesForMovie",
              "requested_slots": [],
              "slot_values": {
                "location": [
                  "San Ramon"
                ],
                "movie_name": [
                  "Teen Spirit"
                ],
                "show_date": [
                  "2nd of March"
                ],
                "show_type": [
                  "3d"
                ],
                "theater_name": [
                  "dontcare"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "No. I want to watch on 2nd of March. What time can i watch?"
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "OFFER",
                "slot": "show_time",
                "values": [
                  "5 pm"
                ]
              },
              {
                "act": "OFFER",
                "slot": "theater_name",
                "values": [
                  "THE LOT City Center"
                ]
              },
              {
                "act": "INFORM_COUNT",
                "slot": "count",
                "values": [
                  "1"
                ]
              }
            ],
            "service": "Movies_1",
            "slots": [
              {
                "exclusive_end": 22,
                "slot": "show_time",
                "start": 18
              },
              {
                "exclusive_end": 45,
                "slot": "theater_name",
                "start": 26
              }
            ]
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "I found 1 show at 5 pm in THE LOT City Center."
      },
      {
        "frames": [
          {
            "service": "Movies_1",
            "slots": [],
            "state": {
              "active_intent": "GetTimesForMovie",
              "requested_slots": [],
              "slot_values": {
                "location": [
                  "San Ramon"
                ],
                "movie_name": [
                  "Teen Spirit"
                ],
                "show_date": [
                  "2nd of March"
                ],
                "show_time": [
                  "5 pm"
                ],
                "show_type": [
                  "3d"
                ],
                "theater_name": [
                  "dontcare"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "Yes. Good"
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "REQ_MORE",
                "slot": "",
                "values": []
              }
            ],
            "service": "Movies_1",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Can i help you with anything else?"
      },
      {
        "frames": [
          {
            "service": "Movies_1",
            "slots": [],
            "state": {
              "active_intent": "NONE",
              "requested_slots": [],
              "slot_values": {
                "location": [
                  "San Ramon"
                ],
                "movie_name": [
                  "Teen Spirit"
                ],
                "show_date": [
                  "2nd of March"
                ],
                "show_time": [
                  "5 pm"
                ],
                "show_type": [
                  "3d"
                ],
                "theater_name": [
                  "dontcare"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "No. Thanks a lot"
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "GOODBYE",
                "slot": "",
                "values": []
              }
            ],
            "service": "Movies_1",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Have a great day"
      }

**Comment by XiaoxueZang** [comment]
Hi Leiyu, thank you for your question. This behavior is intentional because we think that when the user takes the advice from the system, it only agrees with the information that directly relates to its intent, which in this case is to find available time of a movie. A similar question is raised in #14. Please refer to my answer there for more details.

**Comment by Leishuyu-bupt** [comment]
> Hi Leiyu, thank you for your question. This behavior is intentional because we think that when the user takes the advice from the system, it only agrees with the information that directly relates to its intent, which in this case is to find available time of a movie. A similar question is raised in #14. Please refer to my answer there for more details.

Thank you so much
