### ISSUE TITLE
Are the service labels in frames available for multi-domain test set?

### ISSUE THREAD

**Issue by ypruan** [google-research-datasets/dstc8-schema-guided-dialogue#21]
According to the "ReadMe" here, the service labels in frames are unblocked when testing, but it was said that models need to select the relevant APIs concerning the multi-domain dialogues in the task proposal document, so I'm wondering that whether are the service(API) labels in frames available for multi-domain test set?

**Comment by abhirast** [comment]
Thanks for your question. The API selection task is not part of DSTC8, and we will be providing the service labels in the individual frames in the multi-domain test set. Although this is a simplified setting, it provides a fair comparison of model quality with other public datasets.

Please refer to the README file for the most updated information. The task proposal was written before the dataset was created and hence it may have some obsolete information.

**Comment by Damcy** [comment]
@abhirast Can you show us a test input example?

**Comment by Damcy** [comment]
@abhirast Is this input right?
```
{
  "dialogue_id": "9_00000",
  "services": [
    "Events_1",
    "Banks_2"
  ],
  "turns": [
    {
      "frames": [
        {
          "service": "",
          "slots": [],
          "state": {
            "active_intent": "",
            "requested_slots": [],
            "slot_values": {}
          }
        }
      ],
      "speaker": "USER",
      "utterance": "Find me something cool to do."
    }
  ]
}
```

**Comment by abhirast** [comment]
Hi Damcy. The above format look good, except that the "service" field is left populated in the frame.

**Comment by Damcy** [comment]
@abhirast If the "service" field is provided, the multi-service-task is largely degraded to the single-service-task, except for some slots. And task2 and task3 are the same when evaluating.
Only the single-service-task and the multi-service-task are distinguished when evaluating, not task1, 2, 3 any more?

**Comment by abhirast** [comment]
Yes, the multi-service task is a bit simplified, but it has some slot values that are carried over from one service to another, which increases its difficulty. Also, please refer to README for information about the track, including the tasks. The track proposal was written before the dataset was created, hence it is not updated.

**Comment by Damcy** [comment]
@abhirast  OK. Thank you!
