### ISSUE TITLE
Joint Goal evaluation

### ISSUE THREAD

**Issue by vevake** [google-research-datasets/dstc8-schema-guided-dialogue#23]
In situations where the joint goal at turn t is predicted wrong but it may be possible to predict the joint goal at turn t+1. I believe, in joint goal accuracy, all turns after the first wrong prediction are to treated as wrong predictions. I notice that this is not addressed in the evaluation script. Is it normal?

**Comment by abhirast** [comment]
Hi. Thanks for the question. Joint goal accuracy is a standard metric used in dialogue state tracking tasks. We have modified the definition to account for non-categorical slots, where exact matching may be too harsh. Your observation is correct - a mistake in dialogue state in one turn is easy to propagate to subsequent turns, and the joint goal accuracy metric is penalized for all these turns. It is a very harsh metric, and that is why we have also included average goal accuracy, which is slightly more forgiving.

**Comment by vevake** [comment]
The evaluation script does not treat the state predictions occurring in the turns after the first wrong prediction as wrong. This could be biased towards models that take all turns upto time t and predict the complete state and models that make a state update at each turn based on previous predictions.
