### ISSUE TITLE
label error

### ISSUE THREAD

**Issue by Leishuyu-bupt** [google-research-datasets/dstc8-schema-guided-dialogue#24]
Dear organizers,
In dialogue 93_00003, we can't find pets_welcome information in utterances, this session has label mistakes?
`{
    "dialogue_id": "93_00003",
    "services": [
      "Travel_1",
      "Hotels_3"
    ],
    "turns": [
      {
        "frames": [
          {
            "service": "Travel_1",
            "slots": [],
            "state": {
              "active_intent": "FindAttractions",
              "requested_slots": [],
              "slot_values": {}
            }
          }
        ],
        "speaker": "USER",
        "utterance": "I'd like to look up some attractions to see."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "REQUEST",
                "slot": "location",
                "values": []
              }
            ],
            "service": "Travel_1",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Okay. Where should I search?"
      },
      {
        "frames": [
          {
            "service": "Travel_1",
            "slots": [
              {
                "exclusive_end": 29,
                "slot": "location",
                "start": 19
              }
            ],
            "state": {
              "active_intent": "FindAttractions",
              "requested_slots": [],
              "slot_values": {
                "location": [
                  "London, UK"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "Please look around London, UK."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "OFFER",
                "slot": "attraction_name",
                "values": [
                  "30 St Mary Axe (The Gherkin)"
                ]
              },
              {
                "act": "OFFER",
                "slot": "category",
                "values": [
                  "Historical Landmark"
                ]
              }
            ],
            "service": "Travel_1",
            "slots": [
              {
                "exclusive_end": 57,
                "slot": "attraction_name",
                "start": 29
              }
            ]
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "I've heard good things about 30 St Mary Axe (The Gherkin). It is a Historical Landmark."
      },
      {
        "frames": [
          {
            "service": "Travel_1",
            "slots": [],
            "state": {
              "active_intent": "FindAttractions",
              "requested_slots": [],
              "slot_values": {
                "good_for_kids": [
                  "True"
                ],
                "location": [
                  "London, UK"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "That sounds nice. Is there anything else that's kid-friendly?"
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "OFFER",
                "slot": "attraction_name",
                "values": [
                  "Alexandra Palace"
                ]
              },
              {
                "act": "OFFER",
                "slot": "category",
                "values": [
                  "Performing Arts Venue"
                ]
              },
              {
                "act": "INFORM_COUNT",
                "slot": "count",
                "values": [
                  "9"
                ]
              }
            ],
            "service": "Travel_1",
            "slots": [
              {
                "exclusive_end": 69,
                "slot": "attraction_name",
                "start": 53
              }
            ]
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "I've found 9 other attractions. First on the list is Alexandra Palace. It is a Performing Arts Venue."
      },
      {
        "frames": [
          {
            "service": "Travel_1",
            "slots": [],
            "state": {
              "active_intent": "FindAttractions",
              "requested_slots": [
                "free_entry"
              ],
              "slot_values": {
                "good_for_kids": [
                  "True"
                ],
                "location": [
                  "London, UK"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "Is that a free attraction?"
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "INFORM",
                "slot": "free_entry",
                "values": [
                  "False"
                ]
              }
            ],
            "service": "Travel_1",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "No, there is an entry fee there."
      },
      {
        "frames": [
          {
            "service": "Hotels_3",
            "slots": [],
            "state": {
              "active_intent": "SearchHotel",
              "requested_slots": [],
              "slot_values": {
                "location": [
                  "London, UK"
                ],
                "number_of_rooms": [
                  "3"
                ],
                "pets_welcome": [
                  "True"
                ]
              }
            }
          },
          {
            "service": "Travel_1",
            "slots": [],
            "state": {
              "active_intent": "FindAttractions",
              "requested_slots": [],
              "slot_values": {
                "good_for_kids": [
                  "True"
                ],
                "location": [
                  "London, UK"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "Oh, okay. I need to also find a hotel out there. I need to get 3 different rooms."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "OFFER",
                "slot": "hotel_name",
                "values": [
                  "45 Park Lane"
                ]
              },
              {
                "act": "OFFER",
                "slot": "average_rating",
                "values": [
                  "4.7"
                ]
              }
            ],
            "service": "Hotels_3",
            "slots": [
              {
                "exclusive_end": 42,
                "slot": "hotel_name",
                "start": 30
              },
              {
                "exclusive_end": 66,
                "slot": "average_rating",
                "start": 63
              }
            ]
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Sure. What do you think about 45 Park Lane. It has a rating of 4.7."
      },
      {
        "frames": [
          {
            "service": "Hotels_3",
            "slots": [],
            "state": {
              "active_intent": "SearchHotel",
              "requested_slots": [],
              "slot_values": {
                "hotel_name": [
                  "45 Park Lane"
                ],
                "location": [
                  "London, UK"
                ],
                "number_of_rooms": [
                  "3"
                ],
                "pets_welcome": [
                  "True"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "That sounds just fine."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "REQ_MORE",
                "slot": "",
                "values": []
              }
            ],
            "service": "Hotels_3",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Is there anything else I can do to help?"
      },
      {
        "frames": [
          {
            "service": "Hotels_3",
            "slots": [
              {
                "exclusive_end": 46,
                "slot": "check_out_date",
                "start": 33
              }
            ],
            "state": {
              "active_intent": "ReserveHotel",
              "requested_slots": [],
              "slot_values": {
                "check_out_date": [
                  "11th of March"
                ],
                "hotel_name": [
                  "45 Park Lane"
                ],
                "location": [
                  "London, UK"
                ],
                "number_of_rooms": [
                  "3"
                ],
                "pets_welcome": [
                  "True"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "I want to book a hotel until the 11th of March."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "REQUEST",
                "slot": "check_in_date",
                "values": []
              }
            ],
            "service": "Hotels_3",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "When do you expect to check in?"
      },
      {
        "frames": [
          {
            "service": "Hotels_3",
            "slots": [
              {
                "exclusive_end": 38,
                "slot": "check_in_date",
                "start": 22
              }
            ],
            "state": {
              "active_intent": "ReserveHotel",
              "requested_slots": [],
              "slot_values": {
                "check_in_date": [
                  "Monday next week"
                ],
                "check_out_date": [
                  "11th of March"
                ],
                "hotel_name": [
                  "45 Park Lane"
                ],
                "location": [
                  "London, UK"
                ],
                "number_of_rooms": [
                  "3"
                ],
                "pets_welcome": [
                  "True"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "I'll need it starting Monday next week."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "CONFIRM",
                "slot": "hotel_name",
                "values": [
                  "45 Park Lane"
                ]
              },
              {
                "act": "CONFIRM",
                "slot": "location",
                "values": [
                  "London"
                ]
              },
              {
                "act": "CONFIRM",
                "slot": "check_in_date",
                "values": [
                  "March 4th"
                ]
              },
              {
                "act": "CONFIRM",
                "slot": "check_out_date",
                "values": [
                  "March 11th"
                ]
              },
              {
                "act": "CONFIRM",
                "slot": "number_of_rooms",
                "values": [
                  "3"
                ]
              }
            ],
            "service": "Hotels_3",
            "slots": [
              {
                "exclusive_end": 64,
                "slot": "hotel_name",
                "start": 52
              },
              {
                "exclusive_end": 74,
                "slot": "location",
                "start": 68
              },
              {
                "exclusive_end": 93,
                "slot": "check_in_date",
                "start": 84
              },
              {
                "exclusive_end": 115,
                "slot": "check_out_date",
                "start": 105
              }
            ]
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Okay, let me make sure. You want to book 3 rooms at 45 Park Lane in London starting March 4th and ending March 11th."
      },
      {
        "frames": [
          {
            "service": "Hotels_3",
            "slots": [],
            "state": {
              "active_intent": "ReserveHotel",
              "requested_slots": [
                "phone_number"
              ],
              "slot_values": {
                "check_in_date": [
                  "March 4th",
                  "Monday next week"
                ],
                "check_out_date": [
                  "11th of March",
                  "March 11th"
                ],
                "hotel_name": [
                  "45 Park Lane"
                ],
                "location": [
                  "London",
                  "London, UK"
                ],
                "number_of_rooms": [
                  "3"
                ],
                "pets_welcome": [
                  "True"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "That is correct. What's the phone number for the hotel?"
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "INFORM",
                "slot": "phone_number",
                "values": [
                  "+44 20 7493 4545"
                ]
              },
              {
                "act": "NOTIFY_SUCCESS",
                "slot": "",
                "values": []
              }
            ],
            "service": "Hotels_3",
            "slots": [
              {
                "exclusive_end": 58,
                "slot": "phone_number",
                "start": 42
              }
            ]
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "I made your reservation and the number is +44 20 7493 4545."
      },
      {
        "frames": [
          {
            "service": "Hotels_3",
            "slots": [],
            "state": {
              "active_intent": "ReserveHotel",
              "requested_slots": [],
              "slot_values": {
                "check_in_date": [
                  "March 4th",
                  "Monday next week"
                ],
                "check_out_date": [
                  "11th of March",
                  "March 11th"
                ],
                "hotel_name": [
                  "45 Park Lane"
                ],
                "location": [
                  "London",
                  "London, UK"
                ],
                "number_of_rooms": [
                  "3"
                ],
                "pets_welcome": [
                  "True"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "Thanks for the help."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "REQ_MORE",
                "slot": "",
                "values": []
              }
            ],
            "service": "Hotels_3",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Is there anything else you need?"
      },
      {
        "frames": [
          {
            "service": "Hotels_3",
            "slots": [],
            "state": {
              "active_intent": "NONE",
              "requested_slots": [],
              "slot_values": {
                "check_in_date": [
                  "March 4th",
                  "Monday next week"
                ],
                "check_out_date": [
                  "11th of March",
                  "March 11th"
                ],
                "hotel_name": [
                  "45 Park Lane"
                ],
                "location": [
                  "London",
                  "London, UK"
                ],
                "number_of_rooms": [
                  "3"
                ],
                "pets_welcome": [
                  "True"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "No. That will be all."
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "GOODBYE",
                "slot": "",
                "values": []
              }
            ],
            "service": "Hotels_3",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "Have a wonderful day!"
      }
    ]
  },`

**Comment by XiaoxueZang** [comment]
Thanks for finding the issue. It has been fixed.
