### ISSUE TITLE
Unseen labels in dev dataset (which does not exist in train dataset)

### ISSUE THREAD

**Issue by Taekyoon** [google-research-datasets/dstc8-schema-guided-dialogue#3]
Some unseen slot labels and intent labels are in dev dataset, so that a trained machine has to predict new labels which have never occurred in train dataset.

those are the list of unseen labels in dev dataset

```
Unseen intent labels:
{'GetAlarms', 'RentMovie', 'FindAttractions', 'GetWeather', 'AddAlarm'}

Unseen slot labels:
{'director', 'recipient_name', 'starring', 'actors', 'stay_length', 'new_alarm_name', 'transfer_amount, new_alarm_time}
```

**Comment by abhirast** [comment]
Hi. Building dialogue state tracking models for new services is one of the main focuses of this challenge. New services can have unseen intent and slot labels, so this is not a problem with the dataset. The model can make use of the descriptions associated with these labels (intents or slots) to predict them.
