### ISSUE TITLE
Extension for the entry submission deadline 

### ISSUE THREAD

**Issue by jianguoz** [google-research-datasets/dstc8-schema-guided-dialogue#30]
Based on the training process on SGD-All. Is it possible that we have one-week extension for the entry submission deadline?

**Comment by ChenglongChen** [comment]
I have the same question. We start the competition very late, but we are very interested in this task. However, the model training part consumes fairy amount of time despite we still have some interesting ideas yet to try.

**Comment by XiaoxueZang** [comment]
Hi, thanks for your requests. We are extending the submission deadline to Oct 14 (UTC -12). Please feel free to add follow-ups if you have any questions.

**Comment by ChenglongChen** [comment]
Hi, thanks for the response. Just to further confirm about the exact time, does it mean the new ddl will be at 11:59 PM UTC-12, Oct 14 or 11:59 PM UTC-12, Oct 13？

**Comment by Damcy** [comment]
Looks like 11:59 PM UTC-12, Oct 13 (the 14th of October (Anywhere on Earth))?
@XiaoxueZang Extending the submission deadline is unfair to most of the participants.

**Comment by XiaoxueZang** [comment]
@Damcy Thanks for letting us know your concern. It's unlikely that one day is enough to build a model that beats what having been developed over the past 3 months. We extend the deadline to make sure that the participants have enough time to finish training and deal with some unexpected issues.
