### ISSUE TITLE
Is ‘requested slots F1’ required？

### ISSUE THREAD

**Issue by qq775294390** [google-research-datasets/dstc8-schema-guided-dialogue#31]
I did not predict requested slots since this metric is optional to report in the final paper according to README.md. However, when I submit my results, I have to report this metric. So, is ‘requested slots F1’ required or optional？

**Comment by XiaoxueZang** [comment]
Thank you for reporting it. We've updated the form to make "requested slots F1" optional.

**Comment by qq775294390** [comment]
Thank you.
