### ISSUE TITLE
When release the labels of  test set? 

### ISSUE THREAD

**Issue by Leishuyu-bupt** [google-research-datasets/dstc8-schema-guided-dialogue#33]
Dear Organizer,
  Can we get the golden labels of test set to do some ablation studies after evaluation?

**Comment by abhirast** [comment]
We have reopened the form for submitting predictions. Please use it for conducting ablation studies. The form will close on Nov 11, anywhere on earth, and the results will be sent out by Nov 13.

**Comment by Leishuyu-bupt** [comment]
> We have reopened the form for submitting predictions. Please use it for conducting ablation studies. The form will close on Nov 11, anywhere on earth, and the results will be sent out by Nov 13.

Thank you so much. and can you release the test set with golden labels for more research in the future?
