### ISSUE TITLE
how to train on different domains?

### ISSUE THREAD

**Issue by ha-lins** [google-research-datasets/dstc8-schema-guided-dialogue#36]
Hi @abhirast ,

Thanks for your nice dataset and baseline model! Could you pls tell me how to reproduce the experiments on different single domain (i.g., Tab 5 in the paper)? Maybe by setting the FILE_RANGES in the data_utils.py, but it isn't very cool and convenient. 
Thanks!

**Comment by abhirast** [comment]
Thanks for your interest in the dataset. The numbers in table 5 are obtained from the output of the [evaluation script](https://github.com/google-research/google-research/blob/master/schema_guided_dst/evaluate.py) as outlined [here](https://github.com/google-research/google-research/tree/master/schema_guided_dst#evaluation).

**Comment by ha-lins** [comment]
Thanks for your reply. However, the output of the command line is as follows:

`:Dialog metrics: {'active_intent_accuracy': 0.9196847753185782, 'requested_slots_f1': 0.9355218613266905, 'requested_slots_precision': 0.9729683657500559, 'requested_slots_recall': 0.9399731723675385, 'average_goal_accuracy': 0.6822321176491218, 'average_cat_accuracy': 0.5917799752781211, 'average_noncat_accuracy': 0.7189783031718233, 'joint_goal_accuracy': 0.3517834674714957, 'joint_cat_accuracy': 0.5608944742191831, 'joint_noncat_accuracy': 0.4769702193158954}`

It is the result of Single-SGD in Tab 4, but I want to see the results of different domains in Tab 5.
The saved file contains the predicted results of each turn, while I hope to have access to the final results of each domain. 

Could you give more advice? Thanks a lot! @abhirast

**Comment by abhirast** [comment]
Sorry, we noticed that the changes outputting per-domain numbers were not pushed to github. They are pushed in [this commit](https://github.com/google-research/google-research/commit/fe2967fda947c0d26ec3cc03b0b6796217449c4f).

**Comment by ha-lins** [comment]
Thanks a lot!

**Comment by ha-lins** [comment]
Sorry, it doesn't seem to be any changes for outputting results with this commit. Could you pls check it out again?

**Comment by XiaoxueZang** [comment]
Hi, the change in the above commit makes the evaluation script outputting the metrics per domain besides the metrics per service as you wish if we have understood your meaning correctly as you said that "I hope to have access to the final results of each domain." . To be specific, previously you only get the metrics for each service like "Hotel_1",  "Hotel_2" and there can be multiple services in one domain. After the change, you get the metrics for every domain like "Hotel" which is the aggregation of all the services in this domain.
