### ISSUE TITLE
When will the test dataset be released?

### ISSUE THREAD

**Issue by jianguoz** [google-research-datasets/dstc8-schema-guided-dialogue#37]
Hi, we wonder when the test set will be released with ground truth labels?

**Comment by Shuailong** [comment]
Have the same question here!

**Comment by abhirast** [comment]
Thank you for the patience. We are planning to provide a tool for evaluation where you can upload the predictions and get the evaluation result. However, this may take some time to become available. Meanwhile, you may email the model predictions on the test set to schema-guided-dst@google.com. We will run the evaluations on our end and email you the evaluation report.

**Comment by jianguoz** [comment]
Thanks very much!
