### ISSUE TITLE
Fatal Python error: _PySys_BeginInit: <stdin> is a directory, cannot continue

### ISSUE THREAD

**Issue by Thomas-Grenier** [google-research-datasets/dstc8-schema-guided-dialogue#39]
I wanted to test the baseline model SG-DST but when I tried to train the model using this command:

`python -m schema_guided_dst.baseline.train_and_predict \
--bert_ckpt_dir <downloaded_bert_ckpt_dir> \
--dstc8_data_dir <downloaded_dstc8_data_dir> \
--dialogues_example_dir <output_example_dir> \
--schema_embedding_dir <output_schema_embedding_dir> \
--output_dir <output_ckpt_dir> --dataset_split train --run_mode train \
--task_name dstc8_single_domain`

Where:
_downloaded_bert_ckpt_dir_ is _cased_L-12_H-768_A-12_
and _downloaded_dstc8_data_dir_ is train directory containing dialogues and schema json files.

I got this issue:
`Fatal Python error: _PySys_BeginInit: <stdin> is a directory, cannot continue
`
Anyone have the same problem?

**Comment by jianguoz** [comment]
Is your command line correct? e.g., you are using `<uncased_L-12_H-768_A-12>` instead of `uncased_L-12_H-768_A-12`

**Comment by abhirast** [comment]
Hi Thomas. Try running the command with absolute paths for all the directories.

**Comment by Thomas-Grenier** [comment]
Hi guys, 
Yes it was a path problem, thanks for your help.
