### ISSUE TITLE
Non-categorical slot with possible values

### ISSUE THREAD

**Issue by ygabuev** [google-research-datasets/dstc8-schema-guided-dialogue#4]
Hi!

In the train split, the service Restaurants_1 has a slot "cuisine", which is not categorical and at the same time has a list of possible values:

https://github.com/google-research-datasets/dstc8-schema-guided-dialogue/blob/1d268fb9eb0d510f61db0ffb5f62757b95315444/train/schema.json#L1904-L1915

 I believe this should be fixed.

**Comment by AtmaHou** [comment]
Why close this issue?

**Comment by abhirast** [comment]
Thanks for your comment. As mentioned in the README,  possible_values are sometimes provided for non-categorical slots as well. In such cases, the set of provided values is not exhaustive. These values may be used as features in the model.
