### ISSUE TITLE
When release annotation on user action and user goals.

### ISSUE THREAD

**Issue by Leishuyu-bupt** [google-research-datasets/dstc8-schema-guided-dialogue#40]
Hi @abhirast,
Thanks for the valuable dataset. I wonder if the annotation on user action and user goals will be released. It is highly desirable to train a user model with SGD dataset.

**Comment by abhirast** [comment]
Hi @Leishuyu-bupt. Thanks for your question. We are looking into releasing API calls, responses and user actions. They are expected to be available next month.

**Comment by Leishuyu-bupt** [comment]
Hi @abhirast. Thank you very much, that will be interesting.

**Comment by singhaki** [comment]
@abhirast any updates on this?

**Comment by abhirast** [comment]
Done.

**Comment by Leishuyu-bupt** [comment]
> Done.

Thank you very much.
