### ISSUE TITLE
Couldn't reproduce results

### ISSUE THREAD

**Issue by ekmb** [google-research-datasets/dstc8-schema-guided-dialogue#41]
I was able to get 0.486 Joint GA with SGD-S on the dev set stated in the original version of the paper. But the updated paper version now states 0.356 on the test set, while I'm getting only about 0.14. 

Did you get 0.356 with the original checkpoint?
Any changes you made to the model/hyperparams?

Thanks.

**Comment by XiaoxueZang** [comment]
Yes, we got the result using the original checkpoint. We haven't released the golden labels of the test set yet. Did you send us your prediction for evaluation?

Thanks,
Xiaoxue
