### ISSUE TITLE
errors of annotation 

### ISSUE THREAD

**Issue by Leishuyu-bupt** [google-research-datasets/dstc8-schema-guided-dialogue#43]
Dear,
  We find errors of annotation in "83_00069"  in the training set,       {
        "frames": [
          {
            "service": "Restaurants_1",
            "slots": [],
            "state": {
              "active_intent": "ReserveRestaurant",
              "requested_slots": [
                "serves_alcohol"
              ],
              "slot_values": {
                "city": [
                  "san Francisco",
                  "san francisco",
                  "sfo"
                ],
                "cuisine": [
                  "szcheuan"
                ],
                "date": [
                  "march 6th",
                  "the 6th"
                ],
                "party_size": [
                  "1"
                ],
                "restaurant_name": [
                  "bamboo restaurant"
                ],
                "time": [
                  "6:30 in the evening",
                  "6:30 pm"
                ]
              }
            }
          }
        ],
        "speaker": "USER",
        "utterance": "yes that works"
      },
      {
        "frames": [
          {
            "actions": [
              {
                "act": "INFORM",
                "slot": "serves_alcohol",
                "values": [
                  "True"
                ]
              },
              {
                "act": "NOTIFY_SUCCESS",
                "slot": "",
                "values": []
              }
            ],
            "service": "Restaurants_1",
            "slots": []
          }
        ],
        "speaker": "SYSTEM",
        "utterance": "it was succesful"
      },
We think the "requested_slots" is "[]" and then there is no action with "{"act": "INFORM", "slot": "serves_alcohol","values": ["True" ]}"
Thank you for your datasets.

**Comment by XiaoxueZang** [comment]
Hi Shuyu, 

Thank you for reporting the issue. We just fixed the dialogue. 

Thanks,
Xiaoxue
