### ISSUE TITLE
Requested slots are missing in some user turns

### ISSUE THREAD

**Issue by ksurya** [google-research-datasets/dstc8-schema-guided-dialogue#5]
In this example from dialogues_01.json, the user is requesting restaurant name, but its corresponding restaurant_name slot is not annotated

<img width="639" alt="Screen Shot 2019-07-17 at 12 16 37 AM" src="https://user-images.githubusercontent.com/932927/61346756-26863a80-a828-11e9-9a24-4a8fa0a57f59.png">

**Comment by abhirast** [comment]
Thank you for your question. When FIndRestaurants is the active intent, "restaurant_name" is always the requested slot, hence we decided to not annotate it explicitly. Same decision has been made in other services (in train, dev and test sets) as well for consistency.

**Comment by sverdoot** [comment]
@abhirast, Please, may you explain a bit what do you mean by 'always requested'. As far as I understand it's a required slot for given intent, but user may not ask the restaurant name by himself during the dialog and it would be OK. Moreover some required slots may occur in the field 'requested slots', e.g. slot 'location' for the intent 'ReserveHotel'. The question is if there is a way to determine which slots may occur in the 'requested' field?
