### ISSUE TITLE
bug in sgd-x transformation

### ISSUE THREAD

**Issue by zqwerty** [google-research-datasets/dstc8-schema-guided-dialogue#57]
In the original SGD, `Homes` service has a slot called `intent`, however, the [generate_sgdx_dialogues.py](https://github.com/google-research-datasets/dstc8-schema-guided-dialogue/blob/master/sgd_x/generate_sgdx_dialogues.py) does not correctly handle this:
https://github.com/google-research-datasets/dstc8-schema-guided-dialogue/blob/3ad8026d7f002743c083e838657885733aca70dc/sgd_x/generate_sgdx_dialogues.py#L127-L137

which means that the `intent` slot is not transformed for `Homes` (e.g., to `purpose` in sgd-v1)
I think this can be fixed by changing `if action['slot'] == 'intent':` to `if action['slot'] == 'intent' and action['act'] in ['OFFER_INTENT', 'INFORM_INTENT']:`

**Comment by zqwerty** [comment]
Another bug in `sgd_x/utils.py`:

https://github.com/google-research-datasets/dstc8-schema-guided-dialogue/blob/3ad8026d7f002743c083e838657885733aca70dc/sgd_x/utils.py#L57-L65

When the new_key has the same name as another old_key, this will override the old_key before transforming old_key. Actually, it happens in **v5:RentalCars_35**. The mapping has `{"pickup_location": "location_for_rental_retrieval", "city": "pickup_location"}`. When [generate_sgdx_dialogues.py](https://github.com/google-research-datasets/dstc8-schema-guided-dialogue/blob/master/sgd_x/generate_sgdx_dialogues.py) first transform `city` it will override the original `pickup_location`. A fix:

```
def replace_dict_keys_with_mapping(d: Dict[Any, Any],
                                   mapping: Dict[Any, Any]) -> None:
  """Replace dictionary keys in-place based on a mapping."""
  keys = list(d.keys())
  values = [d.pop(k) for k in keys]
  for k, v in zip(keys, values):
    if k in mapping:
      k = mapping[k]
    d[k] = v
```

**Comment by harjlee** [comment]
Hi @zqwerty - sorry for the very delayed response here. Thanks so much for pointing out these issues and also offering up resolutions. We have implemented the corrections now in https://github.com/google-research-datasets/dstc8-schema-guided-dialogue/pull/59 and https://github.com/google-research-datasets/dstc8-schema-guided-dialogue/pull/60
