### ISSUE TITLE
"intent" as a slot

### ISSUE THREAD

**Issue by Lekja00160612** [google-research-datasets/dstc8-schema-guided-dialogue#58]
Hi team,
I was working with SGD_X and figure out in original SGD, test set of service "Homes_2", there is a slot called "intent", which purpose is to express whether user want to buy or rent houses. However with current SGD_X generate code, we handle slot with value "intent" as an intent, therefore, in V1 to V5, we completely missed out the slot cases. 
I would love to make a PR but currently not a google contributor, am asking if you guys can make a commit to fix this bug.

**Comment by harjlee** [comment]
Thanks for pointing this out! This has been updated now: https://github.com/google-research-datasets/dstc8-schema-guided-dialogue/pull/60
